spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - application-oauth.yaml
      - application-ncp.yaml
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 10MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(aDY7D1okxkccvPE9kZk6XZmpxK07cD4poaCeU3DLsJOfD1rCsB5FzvDEN8Y1bQePmSCGgAvL8OM=)
    username: ENC(/hjUBd+M+No2p8plU+7ocg==)
    password: ENC(ulowOhMLazuXDVAwlywccg==)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

